CREATE INDEX "admin_activity_logs_admin_id_idx" ON "admin_activity_logs" USING btree ("adminId");--> statement-breakpoint
CREATE INDEX "admin_activity_logs_action_idx" ON "admin_activity_logs" USING btree ("action");--> statement-breakpoint
CREATE INDEX "admin_activity_logs_resource_idx" ON "admin_activity_logs" USING btree ("resourceType","resourceId");--> statement-breakpoint
CREATE INDEX "admin_activity_logs_created_at_idx" ON "admin_activity_logs" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "admin_activity_logs_admin_action_time_idx" ON "admin_activity_logs" USING btree ("adminId","action","createdAt");--> statement-breakpoint
CREATE INDEX "admin_users_deleted_at_idx" ON "admin_users" USING btree ("deletedAt");--> statement-breakpoint
CREATE INDEX "admin_users_role_idx" ON "admin_users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "admin_users_active_deleted_idx" ON "admin_users" USING btree ("isActive","deletedAt");--> statement-breakpoint
CREATE INDEX "analyses_user_id_idx" ON "analyses" USING btree ("userID");--> statement-breakpoint
CREATE INDEX "analyses_document_id_idx" ON "analyses" USING btree ("documentID");--> statement-breakpoint
CREATE INDEX "analyses_status_idx" ON "analyses" USING btree ("status");--> statement-breakpoint
CREATE INDEX "analyses_job_id_idx" ON "analyses" USING btree ("jobID");--> statement-breakpoint
CREATE INDEX "analyses_user_status_idx" ON "analyses" USING btree ("userID","status");--> statement-breakpoint
CREATE INDEX "analyses_created_at_idx" ON "analyses" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "blocked_users_user_id_idx" ON "blocked_users" USING btree ("userID");--> statement-breakpoint
CREATE INDEX "blocked_users_candidate_id_idx" ON "blocked_users" USING btree ("candidateID");--> statement-breakpoint
CREATE INDEX "blocked_users_active_idx" ON "blocked_users" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "blocked_users_user_active_idx" ON "blocked_users" USING btree ("userID","isActive");--> statement-breakpoint
CREATE INDEX "blocked_users_candidate_active_idx" ON "blocked_users" USING btree ("candidateID","isActive");--> statement-breakpoint
CREATE INDEX "blocked_users_type_idx" ON "blocked_users" USING btree ("userType");--> statement-breakpoint
CREATE INDEX "candidate_analyses_candidate_id_idx" ON "candidate_analyses" USING btree ("candidateID");--> statement-breakpoint
CREATE INDEX "candidate_analyses_document_id_idx" ON "candidate_analyses" USING btree ("documentID");--> statement-breakpoint
CREATE INDEX "candidate_analyses_status_idx" ON "candidate_analyses" USING btree ("status");--> statement-breakpoint
CREATE INDEX "candidate_analyses_job_id_idx" ON "candidate_analyses" USING btree ("jobID");--> statement-breakpoint
CREATE INDEX "candidate_analyses_candidate_status_idx" ON "candidate_analyses" USING btree ("candidateID","status");--> statement-breakpoint
CREATE INDEX "candidate_analyses_created_at_idx" ON "candidate_analyses" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "candidate_documents_candidate_id_idx" ON "candidate_documents" USING btree ("candidateID");--> statement-breakpoint
CREATE INDEX "candidate_documents_deleted_at_idx" ON "candidate_documents" USING btree ("deletedAt");--> statement-breakpoint
CREATE INDEX "candidate_documents_candidate_deleted_idx" ON "candidate_documents" USING btree ("candidateID","deletedAt");--> statement-breakpoint
CREATE INDEX "candidate_documents_created_at_idx" ON "candidate_documents" USING btree ("createdAt");--> statement-breakpoint
CREATE UNIQUE INDEX "candidate_processed_raw_data_analysis_id_idx" ON "candidate_processed_and_raw_data" USING btree ("analysisID");--> statement-breakpoint
CREATE INDEX "candidate_processed_raw_data_document_id_idx" ON "candidate_processed_and_raw_data" USING btree ("documentID");--> statement-breakpoint
CREATE INDEX "candidate_resume_content_candidate_id_idx" ON "candidate_resume_content" USING btree ("candidateID");--> statement-breakpoint
CREATE UNIQUE INDEX "candidate_resume_content_analysis_id_idx" ON "candidate_resume_content" USING btree ("analysisID");--> statement-breakpoint
CREATE INDEX "candidate_resume_content_candidate_analysis_idx" ON "candidate_resume_content" USING btree ("candidateID","analysisID");--> statement-breakpoint
CREATE INDEX "candidate_resume_content_last_edit_type_idx" ON "candidate_resume_content" USING btree ("lastEditType");--> statement-breakpoint
CREATE INDEX "candidate_resume_content_active_rewrite_idx" ON "candidate_resume_content" USING btree ("activeRewriteID");--> statement-breakpoint
CREATE INDEX "candidate_resume_content_updated_at_idx" ON "candidate_resume_content" USING btree ("updatedAt");--> statement-breakpoint
CREATE INDEX "candidate_resume_rewrites_candidate_id_idx" ON "candidate_resume_rewrites" USING btree ("candidateID");--> statement-breakpoint
CREATE INDEX "candidate_resume_rewrites_analysis_id_idx" ON "candidate_resume_rewrites" USING btree ("analysisID");--> statement-breakpoint
CREATE INDEX "candidate_resume_rewrites_content_id_idx" ON "candidate_resume_rewrites" USING btree ("resumeContentID");--> statement-breakpoint
CREATE INDEX "candidate_resume_rewrites_status_idx" ON "candidate_resume_rewrites" USING btree ("status");--> statement-breakpoint
CREATE INDEX "candidate_resume_rewrites_job_id_idx" ON "candidate_resume_rewrites" USING btree ("jobID");--> statement-breakpoint
CREATE INDEX "candidate_resume_rewrites_candidate_status_idx" ON "candidate_resume_rewrites" USING btree ("candidateID","status");--> statement-breakpoint
CREATE INDEX "candidate_resume_rewrites_active_idx" ON "candidate_resume_rewrites" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "candidate_resume_rewrites_content_active_idx" ON "candidate_resume_rewrites" USING btree ("resumeContentID","isActive");--> statement-breakpoint
CREATE INDEX "candidate_resume_themes_candidate_id_idx" ON "candidate_resume_themes" USING btree ("candidateID");--> statement-breakpoint
CREATE UNIQUE INDEX "candidate_resume_themes_content_id_idx" ON "candidate_resume_themes" USING btree ("resumeContentID");--> statement-breakpoint
CREATE INDEX "candidate_resume_themes_theme_id_idx" ON "candidate_resume_themes" USING btree ("themeID");--> statement-breakpoint
CREATE INDEX "candidate_resume_themes_draft_idx" ON "candidate_resume_themes" USING btree ("isDraft");--> statement-breakpoint
CREATE INDEX "candidates_organisation_id_idx" ON "candidates" USING btree ("organisationID");--> statement-breakpoint
CREATE INDEX "candidates_deleted_at_idx" ON "candidates" USING btree ("deletedAt");--> statement-breakpoint
CREATE INDEX "candidates_verified_idx" ON "candidates" USING btree ("isVerified");--> statement-breakpoint
CREATE INDEX "candidates_org_deleted_idx" ON "candidates" USING btree ("organisationID","deletedAt");--> statement-breakpoint
CREATE INDEX "candidates_org_verified_deleted_idx" ON "candidates" USING btree ("organisationID","isVerified","deletedAt");--> statement-breakpoint
CREATE INDEX "candidates_created_at_idx" ON "candidates" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "forgot_password_tokens_user_id_idx" ON "forgot_password_tokens" USING btree ("userID");--> statement-breakpoint
CREATE INDEX "forgot_password_tokens_candidate_id_idx" ON "forgot_password_tokens" USING btree ("candidateID");--> statement-breakpoint
CREATE INDEX "forgot_password_tokens_user_unused_idx" ON "forgot_password_tokens" USING btree ("userID","isUsed");--> statement-breakpoint
CREATE INDEX "forgot_password_tokens_candidate_unused_idx" ON "forgot_password_tokens" USING btree ("candidateID","isUsed");--> statement-breakpoint
CREATE INDEX "forgot_password_tokens_expires_at_idx" ON "forgot_password_tokens" USING btree ("expiresAt");--> statement-breakpoint
CREATE INDEX "forgot_password_tokens_user_type_idx" ON "forgot_password_tokens" USING btree ("userType");--> statement-breakpoint
CREATE INDEX "invites_organisation_id_idx" ON "invites" USING btree ("organisationID");--> statement-breakpoint
CREATE INDEX "invites_email_idx" ON "invites" USING btree ("email");--> statement-breakpoint
CREATE INDEX "invites_accepted_idx" ON "invites" USING btree ("isAccepted");--> statement-breakpoint
CREATE INDEX "invites_expires_at_idx" ON "invites" USING btree ("expiresAt");--> statement-breakpoint
CREATE INDEX "invites_org_pending_idx" ON "invites" USING btree ("organisationID","isAccepted");--> statement-breakpoint
CREATE INDEX "invites_email_org_idx" ON "invites" USING btree ("email","organisationID");--> statement-breakpoint
CREATE UNIQUE INDEX "org_members_user_org_unique_idx" ON "organisation_members" USING btree ("userID","organisationID");--> statement-breakpoint
CREATE INDEX "org_members_user_id_idx" ON "organisation_members" USING btree ("userID");--> statement-breakpoint
CREATE INDEX "org_members_organisation_id_idx" ON "organisation_members" USING btree ("organisationID");--> statement-breakpoint
CREATE INDEX "org_members_role_idx" ON "organisation_members" USING btree ("role");--> statement-breakpoint
CREATE INDEX "org_members_org_role_idx" ON "organisation_members" USING btree ("organisationID","role");--> statement-breakpoint
CREATE INDEX "organisations_creator_id_idx" ON "organisations" USING btree ("creatorID");--> statement-breakpoint
CREATE INDEX "organisations_deleted_at_idx" ON "organisations" USING btree ("deletedAt");--> statement-breakpoint
CREATE INDEX "organisations_country_idx" ON "organisations" USING btree ("country");--> statement-breakpoint
CREATE INDEX "organisations_city_idx" ON "organisations" USING btree ("city");--> statement-breakpoint
CREATE INDEX "organisations_name_idx" ON "organisations" USING btree ("name");--> statement-breakpoint
CREATE INDEX "organisations_created_at_idx" ON "organisations" USING btree ("createdAt");--> statement-breakpoint
CREATE UNIQUE INDEX "processed_raw_data_analysis_id_idx" ON "processed_and_raw_data" USING btree ("analysisID");--> statement-breakpoint
CREATE INDEX "processed_raw_data_document_id_idx" ON "processed_and_raw_data" USING btree ("documentID");--> statement-breakpoint
CREATE UNIQUE INDEX "profiles_user_id_idx" ON "profiles" USING btree ("userID");--> statement-breakpoint
CREATE UNIQUE INDEX "profiles_candidate_id_idx" ON "profiles" USING btree ("candidateID");--> statement-breakpoint
CREATE INDEX "profiles_country_idx" ON "profiles" USING btree ("country");--> statement-breakpoint
CREATE INDEX "profiles_city_idx" ON "profiles" USING btree ("city");--> statement-breakpoint
CREATE INDEX "resume_content_user_id_idx" ON "resume_content" USING btree ("userID");--> statement-breakpoint
CREATE UNIQUE INDEX "resume_content_analysis_id_idx" ON "resume_content" USING btree ("analysisID");--> statement-breakpoint
CREATE INDEX "resume_content_user_analysis_idx" ON "resume_content" USING btree ("userID","analysisID");--> statement-breakpoint
CREATE INDEX "resume_content_last_edit_type_idx" ON "resume_content" USING btree ("lastEditType");--> statement-breakpoint
CREATE INDEX "resume_content_active_rewrite_idx" ON "resume_content" USING btree ("activeRewriteID");--> statement-breakpoint
CREATE INDEX "resume_content_updated_at_idx" ON "resume_content" USING btree ("updatedAt");--> statement-breakpoint
CREATE INDEX "resume_content_created_at_idx" ON "resume_content" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "resume_rewrites_user_id_idx" ON "resume_rewrites" USING btree ("userID");--> statement-breakpoint
CREATE INDEX "resume_rewrites_analysis_id_idx" ON "resume_rewrites" USING btree ("analysisID");--> statement-breakpoint
CREATE INDEX "resume_rewrites_content_id_idx" ON "resume_rewrites" USING btree ("resumeContentID");--> statement-breakpoint
CREATE INDEX "resume_rewrites_status_idx" ON "resume_rewrites" USING btree ("status");--> statement-breakpoint
CREATE INDEX "resume_rewrites_job_id_idx" ON "resume_rewrites" USING btree ("jobID");--> statement-breakpoint
CREATE INDEX "resume_rewrites_user_status_idx" ON "resume_rewrites" USING btree ("userID","status");--> statement-breakpoint
CREATE INDEX "resume_rewrites_active_idx" ON "resume_rewrites" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "resume_rewrites_content_active_idx" ON "resume_rewrites" USING btree ("resumeContentID","isActive");--> statement-breakpoint
CREATE INDEX "resume_rewrites_version_idx" ON "resume_rewrites" USING btree ("versionNumber");--> statement-breakpoint
CREATE INDEX "resume_rewrites_created_at_idx" ON "resume_rewrites" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "resume_themes_category_idx" ON "resume_themes" USING btree ("category");--> statement-breakpoint
CREATE INDEX "resume_themes_public_idx" ON "resume_themes" USING btree ("isPublic");--> statement-breakpoint
CREATE INDEX "resume_themes_ats_idx" ON "resume_themes" USING btree ("isATSOptimized");--> statement-breakpoint
CREATE INDEX "resume_themes_public_category_ats_idx" ON "resume_themes" USING btree ("isPublic","category","isATSOptimized");--> statement-breakpoint
CREATE INDEX "resume_themes_system_idx" ON "resume_themes" USING btree ("isSystemTheme");--> statement-breakpoint
CREATE INDEX "resume_themes_usage_count_idx" ON "resume_themes" USING btree ("usageCount");--> statement-breakpoint
CREATE INDEX "system_settings_category_idx" ON "system_settings" USING btree ("category");--> statement-breakpoint
CREATE INDEX "system_settings_public_idx" ON "system_settings" USING btree ("isPublic");--> statement-breakpoint
CREATE INDEX "system_settings_category_public_idx" ON "system_settings" USING btree ("category","isPublic");--> statement-breakpoint
CREATE INDEX "documents_user_id_idx" ON "documents" USING btree ("userID");--> statement-breakpoint
CREATE INDEX "documents_deleted_at_idx" ON "documents" USING btree ("deletedAt");--> statement-breakpoint
CREATE INDEX "documents_user_deleted_idx" ON "documents" USING btree ("userID","deletedAt");--> statement-breakpoint
CREATE INDEX "documents_created_at_idx" ON "documents" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "user_resume_themes_user_id_idx" ON "user_resume_themes" USING btree ("userID");--> statement-breakpoint
CREATE UNIQUE INDEX "user_resume_themes_content_id_idx" ON "user_resume_themes" USING btree ("resumeContentID");--> statement-breakpoint
CREATE INDEX "user_resume_themes_theme_id_idx" ON "user_resume_themes" USING btree ("themeID");--> statement-breakpoint
CREATE INDEX "user_resume_themes_draft_idx" ON "user_resume_themes" USING btree ("isDraft");--> statement-breakpoint
CREATE INDEX "users_deleted_at_idx" ON "users" USING btree ("deletedAt");--> statement-breakpoint
CREATE INDEX "users_verified_idx" ON "users" USING btree ("isVerified");--> statement-breakpoint
CREATE INDEX "users_verified_deleted_idx" ON "users" USING btree ("isVerified","deletedAt");--> statement-breakpoint
CREATE INDEX "users_created_at_idx" ON "users" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "verify_tokens_user_id_idx" ON "verify_tokens" USING btree ("userID");--> statement-breakpoint
CREATE INDEX "verify_tokens_candidate_id_idx" ON "verify_tokens" USING btree ("candidateID");--> statement-breakpoint
CREATE INDEX "verify_tokens_user_unused_idx" ON "verify_tokens" USING btree ("userID","userType","isUsed");--> statement-breakpoint
CREATE INDEX "verify_tokens_candidate_unused_idx" ON "verify_tokens" USING btree ("candidateID","userType","isUsed");